### ISSUE TITLE
The given data was invalid translate

### ISSUE THREAD

**Issue by wallysonn** [lucascudo/laravel-pt-BR-localization#24]
how to translate "The given data was invalid"?

**Comment by lucascudo** [comment]
"A data fornecida é inválida". Esta frase está no Laravel?

**Comment by luizgdi** [comment]
@lucascudo @wallysonn 
en: I don't think you can translate dinamically since this is static in the code, maybe doing some custom exception that extends that one you can achieve this.
br: Não acho que seja possível traduzir dinamicamente já que no código está estático, talvez fazendo uma exception personalizada que extende aquela ali seja possível.
![validation](https://user-images.githubusercontent.com/43801004/94074235-45d70b00-fdcf-11ea-8ca7-1484fde96ee0.png)

**Comment by lucascudo** [comment]
@wallysonn, unfortunately we can`t add a custom exception is out of the scope for this solution.
@luizgdi thank you for clarifying it.
